# -*- coding: utf-8 -*-
"""Geopandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKYtA9Nje66Yra3Hf2vKatRgehw1YB4P
"""

pip install geopandas

import seaborn as sns
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
sns.set_style('whitegrid')

fp = "/content/drive/My Drive/Igismap/Indian_States.shp" 
map_df = gpd.read_file(fp) ## reading shape file for states of india into dataframe

map_df.head()

data_for_map=pd.read_excel('/content/drive/My Drive/Data_for_map.xlsx',dtype={'sates_name': str, 'positive': float,'negative': float,"neutral":float})

## merging data from shape file and our twitter data using positive and negative tweets
merged = map_df.set_index('st_nm').join(data_for_map.set_index('states_name'))

# plotting map for percentage of negative tweets
fig, ax = plt.subplots(1, figsize=(10, 6))
ax.axis('off')
ax.set_title('State Wise Opposition cases', fontdict={'fontsize': '25', 'fontweight' : '3'})

# plot the figure
merged.plot(column='negative', cmap='YlOrRd', linewidth=0.8, ax=ax, edgecolor='0.8', legend=True)
fig.savefig("negative_state_wise.png", dpi=100)

# plotting map for percentage of positive tweets
fig, ax = plt.subplots(1, figsize=(10, 6))
ax.axis('off')
ax.set_title('State Wise Favourable cases', fontdict={'fontsize': '25', 'fontweight' : '3'})

# plot the figure
merged.plot(column='positive', cmap='YlOrRd', linewidth=0.8, ax=ax, edgecolor='0.8', legend=True)
fig.savefig("posititive_state_wise.png", dpi=100)